name: iconscatalog
description: App for extract your favorites Material Design Icons.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  community_material_icon: ^3.5.95
  cupertino_icons: ^0.1.3  
  path_provider: ^1.6.16
  share: ^0.6.5+1  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
